### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by hussam-dh** [nycto-hackerone/nycto-dork#1]
Hello,
I saw that you are using search-results.com for searching,
The question is:
does this site implement any kind of restriction or filtering on automated crawling?
or you are using something to evade being banned by them?
Thanks

**Comment by hussam-dh** [comment]
Another thing,
did you consider using beautifulsoap for parsing html instead of using regular expressions or there is some of problem when using this library?
Thanks again

**Comment by nycto-hackerone** [comment]
I just run Tor, even though I have to change IPs every so often... I haven't quite got it all worked out yet. The reason of me putting it out to public is for help from others .. and I just wrote it to my best knowledge I'm still learning.

**Comment by hussam-dh** [comment]
Thanks @nycto-hackerone
